[build]
builder = "NIXPACKS"

[build.nixpacksCommands]
buildCommand = "composer install --no-dev --optimize-autoloader --no-interaction"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10