services:
  - type: web
    name: supportly
    env: php
    runtime: php
    region: oregon
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader --no-interaction
    startCommand: php -S 0.0.0.0:$PORT -t public
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production